config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  get 'contacts/create'

  get 'welcome/index'

  get '/foundblanket' => 'welcome#foundblanket'
  post '/foundblanket' => 'welcome#foundblanketform'

  get '/admin' => 'admins#index'
  get '/admins' => 'admins#dash', as: :brand
  post '/admin' => 'sessions#createAdmin', as: :admins_login
  get '/admins/new' => 'admins#new'
  post '/admins/new' => 'admins#create', as: :admins
  get '/admin/dash' => 'admins#dash',as: :admins_dash
  get '/admins/showall' => 'admins#showall'
  get '/admins/showusers' => 'admins#showusers'
  get '/admins/edituser/:id' => 'admins#showOneUser'
  get '/admins/edituser/:id/edit' => 'admins#editUser'
  patch 'admns/edituser/:id' => 'admins#updateUser', as: :admins_update_user
  get '/admins/:id/edit' => 'admins#edit'
  patch '/admin/:id' => 'admins#update', as: :update_admin
  delete '/admins/:id' => 'admins#destroy'
  get '/logout' => 'sessions#sign_out', as: :sign_out
  get '/dash' => 'users#index', as: :users_dash
  post '/checkregistration' => 'welcome#checkblanketregistration'
  resources :users, :blankets
  get '/signin' => 'sessions#new', as: :signin
  post 'signin/user' => 'sessions#createUser'
  get '/register' => 'users#new', as: :register
  get '/blankets/:id/edituser' => 'blankets#edituser'
  post '/blankets/add' => 'blankets#userCreate'
  get '/user/blankets/:id' => 'blankets#userShow'
  patch '/user/blankets/:id/edit' => 'blankets#userUpdate', as: :user_edit_blanket
  post '/user/blankets/destroy/:id' => 'blankets#unregister'

  post '/returnlabel' => 'welcome#makeMailingLabel'
  # You can have the root of your site routed with "root"
   root 'welcome#index'
   post '/contacts' => 'contact_forms#create'
   post '/checkin' => 'users#checkIn'
   get '/map' => 'users#map', as: :map
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admins/dash.html.erb
<% content_for :head do %>
<title>ATDC Admin Dash</title>
<%end%>

<% content_for :body do %>
<div class="row">
	<div class="col-xs-10">
		<h3 style="font-family:monospace"> Welcome, <%= @email %>. Keeping it weird, I trust?</h3>
	</div>
</div>
<%end%>

app/views/admins/edit.html.erb
<% content_for :head do %>
<title>ATDC: Edit Admin Info</title>
<%end%>

  <% content_for :body do %>

  <h2 style="font-family:monospace">Edit Admin:</h2>
  <%= simple_form_for @admin, :url => update_admin_path(@admin, :id => @admin[:id]) do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, value: "Update"%>
  <%end%>

<%end%>

app/views/admins/editUser.html.erb
<% content_for :head do %>
<title>ATDC: Edit Customer Detail</title>
<%end%>


  <% content_for :body do %>
  <h2 style="font-family:monospace">Customer Detail:</h2>
  <%= simple_form_for @user, url: admins_update_user_path do |f|%>
  <%= f.input :first_name %> 
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :address1 %>
  <%= f.input :address2 %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zip %>
  <%= f.button :submit, "Update" %>
  <%end%>
<%end%>

app/views/admins/index.html.erb
<% content_for :head do %>
<title>Austin Tie Dye Co: Admin Login</title>
<%end%>


<% content_for :body do %>
<div class="row">
	<div class="col-sm-10">
		<h2>Admin Login.</h2>
	</div>
</div>
<div class="row">
	<div class="col-sm-10">
	<%= simple_form_for @admin, url: admins_login_path do |f| %>
  	<%= f.input :email %>
  	<%= f.input :password %>
  	<%= f.button :submit, value: "Log In"%>
  </div>
	<%end%>

<%end%>

app/views/admins/new.html.erb
<% content_for :head do %>
<title>ATDC: Create New Admin</title>
<%end%>

  <% content_for :body do %>
  <div class="row">
    <h2>Add an Admin.</h2>
  <%= simple_form_for @admin do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, value: "Create"%>
</div>
  <%end%>

<%end%>

app/views/admins/showOneUser.html.erb
<% content_for :head do %>
<title>ATDC: Customer Detail</title>
<%end%>


  <% content_for :body do %>
  <h2 style="font-family:monospace">Customer Detail:</h2>
  <h4><a href="/admins/edituser/<%=@user.id%>/edit">(Edit?)</a></h4>
  <%= @user.first_name %> <%= @user.last_name %> - <%= @user.email %><br>
  <%= @user.address1 %><br>
  <%= @user.address2 %><br>
  <%= @user.city %>, <%= @user.state %><%= @user.zip %><br>

<%end%>

app/views/admins/showall.html.erb
<% content_for :head do %>
<title>ATDC: All the Admins</title>
<%end%>



  <% content_for :body do %>
  <div class="row">
  <h3 style="font-family:monospace">All yer admins! (Click on an email to update email/password.)</h3>

  <% @admins.each do |a| %>
    <a href="/admins/<%= a.id %>/edit"><%= a.email %></a> <%if a.level == 1%> - Super Admin!<%end%> 
    <% if session[:user_id] != a.id%> | 
    <a href="/admins/<%= a.id%>" data-method="delete" data-confirm="Are you SURE you want to delete this admin?">Delete Admin. PERMANENTLY.</a><%end%><br>
  <%end%>
</div>
<%end%>

app/views/admins/showusers.html.erb
<% content_for :head do %>
<title>Austin Tie Dye Co: Customer List</title>
<%end%>



  <% content_for :body do %>
  <h2 style="font-family:monospace">Customer List! (Click for details).</h2>

  <% @users.each do |user| %>
    <strong><a href="/admins/edituser/<%=user.id%>"><%= user.first_name %> <%= user.last_name %></strong></a>- <%= user.email %> <br>
  <%end%>

<%end%>